name: PR_Test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm_install
        run: npm install
        
      - name: run_test_code
        run: npm test
        